### ISSUE TITLE
[Feature] Should we support aggregated ratio metrics as a base type?

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt_metrics#110]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When working with the internal dbt team, we started brainstorming around the NPS Metric. Historically it is described as `promoter score - detractor score`, with each of those being ratios. 

Our eventual solution was to offload a lot of this logic into the column being used in the metric definition but it got us thinking - what if we did want to support this within the current metrics framework? How could we do so in the most flexible way while remaining consistent with our tenets?

This definitely is just the start of the debate of what should live in metrics versus models but for right now lets assume this information **should** live in metric definitions,

### What Would This Look Like?
We'd most likely need to be able to define "ratio" metrics where both the numerator and denominator were aggregations unto themselves. Here is a really rough mockup

```yml
metrics:
  - name: promoter_score
    label: Promoter Score
    model: ref('reviewers')
    description: "The count of promoters over total people"

    calculation_method: ratio
    ratio_config:
           numerator_calculation_method: count
           numerator_expression: case when person_type = 'promoter' then user_id else null end
           denominator_calculation_method: count
           denominator_expression: user_id

    timestamp: signup_date
    time_grains: [day, week, month]

    dimensions:
      - plan
      - country
```

I **really** don't like the semantic method of defining this metric but .... if the needs must.

### Describe alternatives you've considered

Enforce that **any** aggregation needs to be a metric unto itself, even if it's not **really** useful. In the example of NPS, we could construct:
- Count of customers
- Count of promoters
- Count of detractors
- Promoter score (count of promoters/count of customers)
- Detractor score (count of detractors/count of customers)
- NPS ((Promoter Score - Detractor Score )* 100)

### Who will this benefit?

Anyone who wants to build more complicated ratio metrics without needing X components 

### Are you interested in contributing this feature?

Yep
