### ISSUE TITLE
[Bug] Metric name equal to reserved keyword throws error.

### ISSUE THREAD

**Issue by joris-swapfiets** [dbt-labs/dbt_metrics#124]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When defining the the metric name to be the same as a database reserved keyword an error is thrown. In my case I tried to create a metric called `delta`. In redshift there is also a reserved keyword named the same. The error that was thrown was:
```
12:32:20  Database Error in model delta_month (models/metrics/demo/delta/delta/delta_month.sql)
12:32:20    syntax error at or near "delta"
12:32:20    LINE 483:                     ,(<metric_one> - <metric_two>) as delta
12:32:20                                                                     ^
12:32:20    compiled SQL at target/run/dbt_reporting/models/metrics/demo/delta/delta/delta_month.sql
```

The issue isn't very pressing as a workaround for this would be to rename your metric to a non reserved keyword; `delta` -> `delta_metric`.

### Expected Behavior

The metric would be calculated and the sql generated without error.

### Steps To Reproduce

.yml file
```
metrics:
  - name: delta
    label: Delta

    type: expression
    sql: "{{ metric('<metric_one>') }} - {{ metric('<metric_two>') }}"

    timestamp: timestamp
    time_grains: [day, week, month, year]
```

.sql file
```
select *
from {{ metrics.calculate(
    metric('delta'),
    grain='month',
    start_date='2022-01-01',
    end_date='2022-12-31'
    ) }}
```

### Environment

```markdown
- dbt-adapter & version: dbt-redshift v1.2.1
- dbt_metrics version: v0.3.4
```

### Which database adapter are you using with dbt?

redshift
