### ISSUE TITLE
[Bug] Missing values when calculating metrics with using timestamp columns

### ISSUE THREAD

**Issue by marcbllv** [dbt-labs/dbt_metrics#132]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm tying to calculate metrics using one source table with different filters over one column:

Source table:

```
id | occurred_at           | country
1  | 2022-01-01 00:00:00   | FR
2  | 2022-02-01 00:00:00   | UK
```

We want to count each rows, spliting counts by country. But some rows are missing in the output metrics after running `{{ metrics.calculate()`: if the first metric filters out some dates, then these dates are not computed for the second metric. Here is the output I get:

```
date_month | count_fr_events | count_uk_events
2022-01-01 | 1               | 0
```

Is that a known bug, or am I missing something?

### Expected Behavior

I'd like to have:

```
date_month | count_fr_events | count_uk_events
2022-01-01 | 1               | 0
2022-02-01 | 0               | 1
```

### Steps To Reproduce

My DBT model named `event`:

```sql
-- Bigquery syntax here:
SELECT * FROM UNNEST([
  struct(1 AS id, 'FR' AS country, TIMESTAMP('2022-01-01') as occurred_at),
  struct(2 AS id, 'UK' AS country, TIMESTAMP('2022-02-01') as occurred_at)
])
```

Metrics definition:

```yml
version: 2

metrics:
  - name: count_fr_events
    label: Count number of events in France
    model: ref('event')
    type: count
    sql: id
    timestamp: occurred_at
    time_grains: [month]

    filters:
      - field: country
        operator: '='
        value: '"FR"'


  - name: count_uk_events
    label: Count number of events in UK
    model: ref('event')
    type: count
    sql: id
    timestamp: occurred_at
    time_grains: [month]

    filters:
      - field: country
        operator: '='
        value: '"UK"'
```

And the output metrics table `event_metrics`:

```sql
SELECT
  *
FROM {{
  metrics.calculate(
    [
      metric('count_fr_events'),
      metric('count_uk_events'),
    ],
    grain='month',
  )
}}
```

Then run: `dbt run -s +event_metrics`

### Environment

```markdown
- dbt-adapter & version: dbt-bigquery v1.2.0
- dbt_metrics version: v0.3.6
```

### Which database adapter are you using with dbt?

bigquery
