### ISSUE TITLE
[Bug] aggregating over window with time_grain=day generates 'invalid identifier' error

### ISSUE THREAD

**Issue by JoeryV** [dbt-labs/dbt_metrics#146]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am trying to create the number of weekly active users (WAU) by counting distinct users over a 7 day rolling period. 
My approach is to do this by defining the 'window' field in the metric definition.

dbt run generates the compiled sql which contains the `WHERE` condition `date_day = window_filter_date` in the `[metric]__agregate` cte. 

When calculating the metric with `grain='day'` the field `window_filter_date` does not get defined, however, leading to the following error to occur: 
![Screenshot 2022-10-19 at 12 08 36](https://user-images.githubusercontent.com/25407266/196662586-3e7e7ff0-4204-432b-b68f-c905b086514b.png)

Setting the grain to `grain='week'`, the `window_filter_date` field does get created in the compiled SQL query. Hence, it seems to only be an issue in the context of `grain='day'`.

### Expected Behavior

Expect rolling window aggregations to be available for grain `day` as well.

### Steps To Reproduce

**metric_defintion.yml**
```
version: 2

metrics:
  - name: active_users
    label: Active Users
    model: ref('fct_sign_ins')
    description: "The weekly active users."

    calculation_method: count_distinct
    expression: dim_user_id

    timestamp: dim_date_day
    time_grains: [day, week, month, quarter, year]

    window:
      count: 7
      period: day
```

**metric_calculation.sql**
``` 
WITH wau_metric AS (
    SELECT
        *
    FROM
        {{
            metrics.calculate(
                metric('active_users'),
                grain='day',
            )
        }}
) 

SELECT
    * 
FROM
    wau_metric
```

### Relevant log output

```shell
> dbt run


09:51:57  Database Error in model active_users_metric (models/marts/product/active_users_metric.sql)
09:51:57    000904 (42000): SQL compilation error: error line 75 at position 19
09:51:57    invalid identifier 'WINDOW_FILTER_DATE'
09:51:57    compiled Code at target/run/channext/models/marts/product/active_users_metric.sql
09:51:57  
09:51:57  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
```
```


### Environment

```markdown
- dbt-adapter & version: dbt-snowflake v1.3.0
- dbt_metrics version: v1.3.0
```

### Which database adapter are you using with dbt?

snowflake
