### ISSUE TITLE
[Feature] Enable secondary_calculations for expression metrics

### ISSUE THREAD

**Issue by wverheul** [dbt-labs/dbt_metrics#148]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We'd like to create a period-to-date calculation on an expression metric, like for instance a ratio. At the moment the secondary_calculation functionality implements such period-to-date calculations but only works on base metrics (e.g. sums, counts, etc.). 

When trying to use it with expression metrics the secondary_calculation will do:
1) calculate base metrics A and B
2) calculate ratio over metrics A and B
3) calculate cumulative sum over ratio metric for period X

Problem: the ratio is being summed.

Instead, we'd like to see:
1) calculate base metrics A and B
2) calculate cumulative sum over base metrics A and B for period X
3) calculate the ratio over the cumulative sums of A and B

## Example: quarter-to-date ratio metric

For a team's quarterly OKR we use on-time delivery ratio as a key result metric. We want to track this quarter-to-date in order to understand if this metric is reaching our quarterly ambition.

We have a table with the following lay-out which we use as an input table for the metric calculation:

Table name: `input_table`

| delivery_date | delivery_id | on_time |
| ---- | -------- | ---------- |
|2022-01-01|1|True|
|2022-01-01|2|False|
|2022-01-01|3|False|
|2022-01-02|4|True|
|2022-01-02|5|True|
|2022-01-02|6|False|
|...|....|...|

First, we create two base metrics in order to derive the on-time ratio:

```yaml
version: 2

metrics:
  - name: deliveries
     model: ref('input_table')
     description: Count of deliveries
     type: count
     sql: delivery_id
     timestamp: delivery_date
     time_grain: [day, quarter]

  - name: on_time_deliveries
     model: ref('input_table')
     description: Count of on-time deliveries
     type: count
     sql: delivery_id
     timestamp: delivery_date
     time_grain: [day, quarter]
     filters:
       - field: on_time
         operator: 'is'
         value: 'true'
```

Next we add an expression metric based on top of these two base metrics to calculate the on-time ratio:

```yaml
version: 2

metrics:
  - name: deliveries
     ....

  - name: on_time_deliveries
     ...

  - name: on_time_delivery_ratio
     description: Ratio of on-time deliveries
     type: expression
     sql: "{{ metric('on_time_deliveries') }} / {{ metric('deliveries') }}"
     timestap: delivery_date
     time_grain: [day, quarter]
```

By invoking the `metrics.calculate()` macro from `dbt-metrics` we are able to calculate the on-time delivery ratio metric. The `secondary_calculation` functionality allows for adding a quarter-to-date calculation to it:

```python
{{
    metrics.calculate(
        metric('on_time_delivery_ratio'),
        grain='day',
        secondary_calculations=[
            metrics.period_to_date(aggregate="sum", period="quarter", alias="qtd")
	      ]
    )
}}
```

### Output

The following table shows the output of this metric calculation. We can see that the quarter-to-date calculation (`on_time_delivery_ratio_qtd`) sums over the ratios.

| date_day | date_quarter | on_time_deliveries | deliveries | on_time_delivery_ratio | on_time_delivery_ratio_qtd |
| ---------| ------------ | ------------------ | ---------- | ---------------------- | -------------------------------------- |
| 2022-01-01 | 2022-01-01 | 1 | 3 | 0.333 | 0.333 |
| 2022-01-02 | 2022-01-01 | 3 | 3 | 1.0 | 1.333 |
|...|...|...|...|...|...|

### Preferred output

We would prefer the quarter-to-date ratio calculation to first do a quarter-to-date cumulative sum of the base metrics ( `on_time_deliveries_qtd` & `deliveries_qtd` in the table below) and subsequently a SAFE_DIVIDE over these metrics to come to the quarter-to-date ratio (`on_time_delivery_ratio_qtd`).

| date_day | date_quarter | on_time_deliveries | deliveries | on_time_delivery_ratio | on_time_deliveries_qtd | deliveries_qtd | on_time_delivery_ratio_qtd |
| ---------| ------------ | ------------------ | ---------- | ---------------------- | ---------------------- | -------------- | -------------------------- |
| 2022-01-01 | 2022-01-01 | 1 | 3 | 0.333 | 1 | 3 | 0.333 |
| 2022-01-02 | 2022-01-01 | 3 | 3 | 1.0 | 4 | 6 | 0.666 |
|...|...|...|...|...|...|...|...|

### Describe alternatives you've considered

At the moment we have the following workaround:
1. Create quarter-to-date metrics for `on_time_deliveries` and `deliveries` with `secondary_calculations` from `dbt-metrics`
1. Do the ratio calculation on the quarter-to-date metrics in separate SQL logic (not using dbt metrics)

**Example:**
```sql
WITH 
    quarter_to_date_metrics AS (
        SELECT 
            *
        FROM
            {{
                metrics.calculate(
                    [metric('on_time_deliveries'), metric('deliveries')],
                    grain='day',
                    secondary_calculations=[
                        metrics.period_to_date(aggregate="sum", period="quarter", alias="qtd")
	                  ]
                )
            }}
)

SELECT
    quarter_to_date_metrics.*,
    SAFE_DIVIDE(on_time_deliveries_qtd, deliveries_qtd) AS 'on_time_delivery_ratio_qtd'
FROM 
    quarter_to_date_metrics
```

Obviously, we'd love to have dbt metrics as our central way for defining ratio metrics, instead of having to apply post-processing logic to metric calculations.
