### ISSUE TITLE
[Bug] window with time_grain=day extends beyond current date

### ISSUE THREAD

**Issue by JoeryV** [dbt-labs/dbt_metrics#187]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using a rolling window extends past the current date into the future.

The following:
```
  - name: weekly_active_per_day
    label: rolling weekly active users
    description: "The number of active users in the last 7 days"
    model: ref("fct_sign_ins")
    timestamp: dim_date_day
    time_grains: [day]
    calculation_method: count_distinct
    expression: dim_user_id
    window:
      count: -7
      period: day
```

with the current date being `2022-11-18`, this query will result in the following output:
![Screenshot 2022-11-18 at 16 58 52](https://user-images.githubusercontent.com/25407266/202747466-5da52730-1ded-4d2a-8b8e-1f80ac26e2f1.png)

As can be seen, the query extends 7 days into the future.

### Expected Behavior

The max date in the output would be the current date.

### Steps To Reproduce

```
{% set my_metric_yml -%}
{% raw %}

metrics:
  - name: weekly_active_per_day
    label: rolling weekly active users
    description: "The number of active users in the last 7 days"
    model: ref("fct_sign_ins")
    timestamp: dim_date_day
    time_grains: [day]
    calculation_method: count_distinct
    expression: dim_user_id
    window:
      count: 7
      period: day

{% endraw %}
{%- endset %}


select * 
from {{ metrics.develop(
        develop_yml=my_metric_yml,
        metric_list=['weekly_active_per_day'],
        grain='day'
        )
    }}

```

### Environment

```markdown
- dbt-adapter & version: dbt-snowflake==1.3.0
- dbt_metrics version: v1.3.1
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Reason for this bug is probably caused in `genbase_query.sql` ? The date in the base_model is defined as being relative to `calendar_table.date_day` instead of the reverse.

![Screenshot 2022-11-18 at 17 03 06](https://user-images.githubusercontent.com/25407266/202748312-9c6b6656-2fbf-43c5-8161-a4f212eaeeb6.png)
