### ISSUE TITLE
[SEMANTIC-107] [Bug] <Running Into Compilation Error on Metrics >

### ISSUE THREAD

**Issue by edwardlim26** [dbt-labs/dbt_metrics#197]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The compiler returns `

`> " Compilation Error in model key_kpis (models\aggregation\key_kpis.sql) The name argument to ref() must be a string, got <class 'list'>"`

when I tried running the metrics on one of my models. 
![image](https://user-images.githubusercontent.com/110023543/205073490-928e3c04-9e2a-4283-88d9-94179f825db8.png)

### Expected Behavior

I should be able to see a table from the metrics I have added. 

### Steps To Reproduce

1. In my own virtual environment dbt, I add this code snippet to my schema.yml
```
metrics:
  - name: gross_deposits
    label: Gross Deposits
    model: ref('deposits')
    description: "Sum of amount_usd for Deposits"

    calculation_method: sum
    expression: amount_usd 

    timestamp: transfer_ts
    time_grains: [day, week, month, quarter, year, all_time]

    dimensions:
      - registration_country
    
    window:
      count: 4
      period: week

    config:
      enabled: True
```

2. I query it with
```
 {{ config(
     materialized='table',
   )}}
   
select * 
from {{ metrics.calculate(
    metric('gross_deposits'),
    grain='week',
    dimensions=['registration_country']
) }}
```

in a separate .sql file.

3. I use a  _dbt run_ on my terminal to run the file.

### Environment

```markdown
- dbt=1.3.1
- dbt_metrics version: 1.3.2
```

### Which database adapter are you using with dbt?

bigquery
