### ISSUE TITLE
[SEMANTIC-135] [Feature] Support `source` macro in dbt_metrics`model` configuration

### ISSUE THREAD

**Issue by hoangvu-ct** [dbt-labs/dbt_metrics#201]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt metrics should support `source` macro in `model` configuration. Example:
```yaml
metrics:
  - name: rolling_new_customers
    label: New Customers
    model: source('jaffle_shop', 'customers')
    [description](https://docs.getdbt.com/reference/resource-properties/description): "The 14 day rolling count of paying customers using the product"
```

### Reason

Current version of dbt metrics throws an compilation error when use `source` macro in place of `model`. So if we want to use a fact table from other system,  we need to create a wrapper model (view or table) in `dbt`, then `ref` it in the `model` configuration. This is troublesome.

### Describe alternatives you've considered

Create a wrapper model (view or table) in `dbt`, then `ref` it in the `model` configuration. 

### Who will this benefit?

Users that have fact tables that comes from other systems.

### Are you interested in contributing this feature?

Definitely
