### ISSUE TITLE
[SEMANTIC-166] [Bug] Derived metrics don't respect filters

### ISSUE THREAD

**Issue by tomtaylor** [dbt-labs/dbt_metrics#215]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When creating a derived metric with a common field, setting a filter on that field doesn't filter the derived metric.

### Expected Behavior

The derived metric applies the filter successfully or errors with a warning that the filter cannot be applied.

### Steps To Reproduce

I'm running DBT metrics 1.4.0. The metric references here all have a `purpose` dimension, but the outcome ignores this.

```yaml
  - name: combined_ads_spend_for_example
    label: Combined Ads Spend For Example
    description: The total amount spent on ads for [example], across all platforms

    calculation_method: derived
    expression: "{{ metric('facebook_spend') }} + {{ metric('tiktok_spend') }} + {{ metric('snapchat_spend') }}"

    timestamp: date_day
    time_grains: [day, week, month, quarter, year, all_time]

    filters:
      - field: purpose
        operator: "="
        value: "'example'"
```

```sql
{{ config(
  materialized = 'table'
)}}

select * 
from {{ metrics.calculate(
    metric('combined_ads_spend_for_example'),
    grain='day'
) }}
```

### Environment

```markdown
- dbt-adapter & version: dbt-bigquery 1.4.0
- dbt_metrics version: 1.4.0
```

### Which database adapter are you using with dbt?

bigquery
