### ISSUE TITLE
[SEMANTIC-214] [Bug] Derived metrics are not NULL safe

### ISSUE THREAD

**Issue by JoeryV** [dbt-labs/dbt_metrics#226]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`Metric A` looks at what has occurred already.
`Metric B` looks at what is planned for the future.
`Metric C = Metric A + Metric B`, aka metric C is a derived metric.

The definitions of these metrics means that except for the current period, the dates in `Metric A` are disjoint from those in `Metric B`.

The derived metric does not take this into account as can be seen in the screenshot. It tries do do `NULL + 2` in row 10, resulting in `NULL`. 

<img width="781" alt="Screenshot 2023-03-15 at 09 26 40" src="https://user-images.githubusercontent.com/25407266/225269675-b2936225-06dc-49d4-b56b-617dc9152a7c.png">

### Expected Behavior

The expected output in row 10 is `2`.

### Steps To Reproduce

The metrics look like the following:
```
  - name: metric_a
    model: ref("metric_mart")
    calculation_method: count_distinct
    expression: id
    timestamp: dim_date
    time_grains: [day, week, month, quarter, year, all_time]
    dimensions:
      - dimension
    filters:
      - field: is_published
        operator: '='
        value: 'true'


  - name: metric_b
    model: ref("metric_mart")
    calculation_method: count_distinct
    expression: id
    timestamp: dim_date
    time_grains: [day, week, month, quarter, year, all_time]
    dimensions:
      - dimension
    filters:
      - field: is_scheduled
        operator: '='
        value: 'true'


  - name: metric_c
    calculation_method: derived
    expression: "{{ metric('metric_a') }} + {{ metric('metric_b') }}"
    timestamp: dim_date
    time_grains: [day, week, month, quarter, year, all_time]
    dimensions:
      - dimension
```

### Environment

```markdown
- dbt-adapter & version: dbt-snowflake 1.3.0
- dbt_metrics version: 1.3.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by JoeryV** [comment]
I also tried using the following:

```
    - name: metric_c
      calculation_method: derived
      expression: "{{ COALESCE( metric('metric_a') }}, 0 ) + COALESCE( {{ metric('metric_b') }} , 0)"
      timestamp: dim_date
      time_grains: [day, week, month, quarter, year, all_time]
      dimensions:
        - dimension
```

But this results in a complication error:
<img width="479" alt="Screenshot 2023-03-15 at 11 55 02" src="https://user-images.githubusercontent.com/25407266/225288437-5c380d2c-5949-4b7b-a3e1-df543bc1e9ee.png">

The compiled code then looks like:
```
, join_metrics__999 as (

    select 
    
        first_join_metrics.*
        , ( COALESCE( metric_a , 0  + COALESCE(  metric_b  , 0) as metric_c
    from first_join_metrics


)
```

i.e. it messes up the brackets.
