### ISSUE TITLE
[SEMANTIC-232] [Regression] dbt_metrics_default_calendar on redshift fails to build with "can't execute an empty query" starting in 1.4.1

### ISSUE THREAD

**Issue by kylezeeuwen** [dbt-labs/dbt_metrics#229]
### Is this a regression in a recent version of dbt_metrics?

- [X] I believe this is a regression in dbt_metrics functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

when i `dbt run` my project (that has metrics and metrics.calculate usage) I get the following failure:

```
Database Error in model dbt_metrics_default_calendar (models/dbt_metrics_default_calendar.sql)[0m
can't execute an empty query
compiled Code at target/run/metrics/models/dbt_metrics_default_calendar.sql
```

### Expected/Previous Behavior

the `dbt run` should succeed

### Steps To Reproduce

Note I wrote this up here as well : https://getdbt.slack.com/archives/CBSQTAPLG/p1680218676837929

dbt-core=1.4.5
dbt-redshift=1.4.0

packages.yml

```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: dbt-labs/audit_helper
    version: 0.8.0
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/metrics
    version: 1.4.1
  - package: calogica/dbt_expectations
    version: 0.8.4
```

1. run `dbt run` and get failure
2. change to dbt-metrics 1.4.0 via package.yml change then `dbt deps`
3. run `dbt run and get pass

I believe this is related to the casing mismatch of column names between these two files:
* https://github.com/dbt-labs/dbt_metrics/blob/main/models/dbt_metrics_default_calendar.yml
* https://github.com/dbt-labs/dbt_metrics/blob/main/models/dbt_metrics_default_calendar.sql

this is described by Jeremy Cohen in a comment on this bug report : https://github.com/dbt-labs/dbt-core/issues/5183#issuecomment-1112081345

### Environment

```markdown
- dbt-adapter & version: dbt-redshift 1.4.0 and dbt-core 1.4.5
- dbt_metrics (working version): 1.4.0
- dbt_metrics (regression version): 1.4.1
```

### Which database adapter are you using with dbt?

redshift

**Comment by kylezeeuwen** [comment]
Further this bug only occurs if you have persist_docs at the column setup in your dbt_project

the compiled and run versions of the model sql is fine. 
The error occurs post model creation when DBT is attempting to persist the docs to redshift table metadata.
Note (i will update bug report) our dbt_project.yml

```
models:
  +persist_docs:
    relation: true
    columns: true
```

confirmed.
* 1.4.1 with +persist_docs :boom: (can’t execute an empty query)
* 1.4.1 with NO +persist_docs :white_check_mark:
