### ISSUE TITLE
`OR` clause in the Filters for Metrics

### ISSUE THREAD

**Issue by shubh24** [dbt-labs/dbt_metrics#24]
As mentioned in the [dbt Docs](https://docs.getdbt.com/docs/building-a-dbt-project/metrics#filters), all filters in the current metric definition are combined via AND clauses -- and it is suggested to include complex logic in the models powering the metrics.

From `get_metric.sql`, I can see that the filter conditions are built in a forloop using the field, operator and value
```
    where 1=1
    {%- for filter in metric.filters %}
        and {{ filter.field }} {{ filter.operator }} {{ filter.value }}
    {%- endfor %}
```

Although we can build complex filtering logic in the models, it would require us to specify a separate model for each use case -- rather than just defining separate metrics on top of one base model. I was wondering if we could implement `OR` clauses in addition to `AND` as [Polish notation](https://en.wikipedia.org/wiki/Polish_notation) within `get_metric.sql` in a recursive fashion. 

A use case where we have come across a need for an OR clause in the filters:

- Get the count of users who have made late payments OR have cancelled their subscriptions for all users subscribed in the last 30 days. This would look something like 

```
(user.signup_date >= '2022-02-01') AND (user.did_late_payment is True OR user.status = 'canceled')
```

The corresponding filter could look something like this:
```
    filters:
      - join_clause_by: AND
      - clauses:
        - field: signup_date
          operator: '>='
          value: "'2022-02-01'"
        - join_clause_by: OR
        - clauses:
          - field: did_late_payment
            operator: 'is'
            value: 'true'
          - field: status
            operator: '='
            value: "'canceled'"
```

Not sure if this is a priority right now, but thought of sharing this just in case!
